### ISSUE TITLE
self-updating deployments

### ISSUE THREAD

**Issue by philips** [kubernetes-incubator/spartakus#11]
It would be great if spartakus would be able to update its own deployment and ideally we could roll out the update in a controlled manner with a feedback loop. Also, it would be cool if people could subscribe to alpha/beta/stable reporting channels.

We are building something that plugs into an Omaha server for the etcd and Prometheus Operator. Would that be OK for spartakus?

**Comment by philips** [comment]
The Omaha thingie could probably just be a sidecar that takes a deployment and can only update the tag of the spec.container.image.

**Comment by thockin** [comment]
Self-updating makes me nervous.  It is somewhat antithetical to hermetic
containers.

**Comment by errordeveloper** [comment]
@philips wouldn't it be better to use the API? For example, we could consider a cron job type of sidecar that is able to update image in a deployment spec. However, having said this, would Spartakus   benefit from such functionality in significant way really?

**Comment by philips** [comment]
@errordeveloper sure, the cron job needs to talk to Omaha or something that tells it what version to run though. Cron jobs aren't ideal because you want exponential backoffs.
