### ISSUE TITLE
Expired/invalid TLS certificate

### ISSUE THREAD

**Issue by mgoodness** [kubernetes-incubator/spartakus#16]
Upon running spartakus, the logs show:
```
E1229 17:26:30.118403       1 volunteer.go:68] failed sending report: HTTP request failed: Post https://spartakus.k8s.io/api/v1: x509: certificate has expired or is not yet valid
```

**Comment by philips** [comment]
Looks like it expired 23 days ago. cc @thockin

**Comment by thockin** [comment]
@ixdy - we missed one.  dammit.

**Comment by ixdy** [comment]
d'oh. I can fix.

**Comment by thockin** [comment]
you're a prince.  Is this scripted somewhere?

**Comment by ixdy** [comment]
Not yet, but most of the hard work is automated away by https://github.com/xenolf/lego:
```console
$ cd <some_private_dir>
$ GCE_PROJECT=<project> lego --email=<email> --dns=gcloud --domains=foo.k8s.io --domains=foo.kubernetes.io run
...
Server responded with a certificate.
$ cd .lego/certificates
```

and then manually update secrets.

**Comment by thockin** [comment]
I am AFK rest of today - do you have time and access enough top push this
before EOY?

**Comment by ixdy** [comment]
I just updated the secret. It looks like spartakus is using Ingress, so it should be fixed momentarily.

**Comment by ixdy** [comment]
as in now

**Comment by ixdy** [comment]
I'm hoping at some point there will be some more production-ready integration between LE and Kubernetes.

For now, it's ~10m of effort to update all of our certs quarterly, and now spartakus is on my radar.

**Comment by thockin** [comment]
THANKS!!!

**Comment by yuvipanda** [comment]
Should this be closed? :)
