### ISSUE TITLE
Tag v1.1.0 and build new images

### ISSUE THREAD

**Issue by squat** [kubernetes-incubator/spartakus#21]
@thockin I'd like to release v1.1.0 of Spartakus given the new features that were added recently, namely:
* kubernetes client bump to 1.5.1;
* cloud provider reporting; and
* support for extensions reporting.

Thoughts? Is there anything else you'd like to accomplish before tagging a new version?

**Comment by squat** [comment]
ping @thockin

**Comment by thockin** [comment]
nope, how do we want to cut a release?  Do you want to do a build and test, then push somewhere so I can tag and re-push?  We still don't have granular enough access to GCR to let you push directly (it's on the list :)

Or I can just do a tag, build, push cycle.

It would be nice to get a RELEASE.md file or something documenting it.

**Comment by thockin** [comment]
oh snap.  we already HAVE a RELEASE.md :)

**Comment by thockin** [comment]
Release is cut.

**Comment by squat** [comment]
Awesome :) thanks Tim
