### ISSUE TITLE
Inquiry: Intention of Timestamp structure

### ISSUE THREAD

**Issue by brianredbeard** [kubernetes-incubator/spartakus#29]
In `pkg/volunteer/volunteer.go` the Timestamp collected is being cast to a string

 https://github.com/kubernetes-incubator/spartakus/blob/633430c4022c62dc1046682c7f3d3976eb783c60/pkg/volunteer/volunteer.go#L123 

This is similarly defined in the schema `pkg/database/bigquery.schema.json`:

https://github.com/kubernetes-incubator/spartakus/blob/633430c4022c62dc1046682c7f3d3976eb783c60/pkg/database/bigquery.schema.json#L7-L11

As the service is primarily defined  to utilize BigQuery as a datastore it seems odd to utilize a string versus a `TIMESTAMP` (or even an `INTEGER` since BigQuery stores this as `int64`).

Was the use of `String` an intentional design decision?  What are the ramifications of changing this to a field of type Timestamp?

**Comment by thockin** [comment]
It was not intentional.  We can probably do it compatibly - add a new
field, have the server prefer the new field, and IFF the old field is
needed, parse it back to a timestamp?

**Comment by brianredbeard** [comment]
That should likely work.  I first started exploring this a few weeks ago and [took some notes on the BigQuery process](https://gist.github.com/brianredbeard/0c584864a4fb6fc42e6944b0db242963).  I hadn't considered the process of just migrating to a new field though (which really is probably the correct answer).

**Comment by brianredbeard** [comment]
@thockin this has been quite a while.  if i was to submit a PR to add the new field, would that work for you?
