### ISSUE TITLE
Collect stats on namespaces

### ISSUE THREAD

**Issue by thockin** [kubernetes-incubator/spartakus#3]
- Number of namespaces
- Histogram or average age of namespaces
- Histogram or average number of (pods, services, deployments, jobs) per namespace

**Comment by kenan435** [comment]
@thockin Any of you guys implementing this already? I have few of those namespace features already coded. I can finish the rest and make a PR.

**Comment by thockin** [comment]
Nobody is working on this yet.  I'd be happy to review.  This is the sort
of thing that can be added as a series of very small commits, which makes
reviews easy :)

**Comment by dasmb** [comment]
@kenan435 With the counts here, do you plan to provide the "last count," "average" or a histogram?

I believe histograms are the most powerful option, but don't know if there is a good histogram library for Golang.

**Comment by thockin** [comment]
I specifically meant a histogram, though we should make sure we have enough data points to do interesting analyses.

**Comment by kenan435** [comment]
@dasmb, @thockin Please look at the README.md in my PR https://github.com/kubernetes-incubator/spartakus/pull/6/files#diff-04c6e90faac2675aa89e2176d2eec7d8R113 
I have a sample .json output there. Basically we have a histogram for each k8s object we are monitoring. (Jobs, Svc, Deploy etc...). So if, for example, we have 100 jobs we would split that up into several buckets and collect info about each of the buckets.
