### ISSUE TITLE
Move to Go dep

### ISSUE THREAD

**Issue by mhausenblas** [kubernetes-incubator/spartakus#32]
Currently, Spartakus is using Godeps, it would be rad to move to [dep](https://golang.github.io/dep/).
I'm happy to take care of this, if desired.

**Comment by thockin** [comment]
No objection

**Comment by squat** [comment]
sgtm!

**Comment by mhausenblas** [comment]
Cool. Anyone cares to assign it to me then? :)

**Comment by mhausenblas** [comment]
Closing, since it doesn't make any sense, now that there is a different blessed way to manage dependencies.
