### ISSUE TITLE
Archive this project

### ISSUE THREAD

**Issue by fejta** [kubernetes-incubator/spartakus#38]
It does not appear like we are doing much with this data. Let's turn it down in the utility cluster and archive this project.

/assign @fejta @thockin

**Comment by aronchick** [comment]
Well, FWIW, Kubeflow uses this very heavily.

/cc @jlewi

**Comment by fejta** [comment]
Note that the last PR was March 2018, last closed issue was April 2017.

So this is two things we want to stop supporting:
* the instance in the kubernetes community utility cluster
* the codebase

I assume kubeflow is running their own instance? If they need this then how about we move the repo into the kubeflow org?

**Comment by thockin** [comment]
I have had a couple nibbles about restarting the work.  I don't want to nuke this just yet, but we can turn down the current instance that is running, at least.

**Comment by squat** [comment]
Likewise, I’ve had quite some ideas about potential for reinvesting in this project especially given some of the overlap and lessons learned from working on telemetry for OpenShift.

**Comment by jlewi** [comment]
Kubeflow is running its own instance of spartakus so we don't depend on the test cluster that @fejta wants to shutdown.

**Comment by thockin** [comment]
I scaled the collector to 0 - should have no detrimental impact on anyone
running the volunteer.

**Comment by brianredbeard** [comment]
Speaking of this, if most instances have been scaled to 0, possibly this is a good opportunity to retool #29 (Intention of Timestamp structure).  

Thoughts?
