### ISSUE TITLE
List of things I'd like to know about how people are using Kubernetes

### ISSUE THREAD

**Issue by dasmb** [kubernetes-incubator/spartakus#7]
I'm very excited to see this project. I've been mentioning around the office for weeks that the community needs a better idea of how K8s is actually being used.

I'd like to help expand the project to collect more useful information about installations. Here's a dump of the things I've been wondering about that we could collect. I'd be willing to add any of these or help in the collection & anonymization of other datapoints.

Context (_these would likely need to be provided in plain text at launch time, so wouldn't want to ask a lot_)
- Phase of cluster (e.g. prototype, development, staging, production)
- Installed in private datacenter or (specific) public cloud?

Cluster setup
- Master node count
- Etcd node count 
- Service node count
- Node volatility, how quickly are nodes added or removed from the cluster?
- Node consistency [specifically I wonder if master/etcd nodes are sized the same as other nodes]
- Are Etcd nodes also worker nodes (cf self hosting)

Networking
- Block size of Pod & Service networks
- Is an overlay network being used
- Is policy enabled
- Is CNI being used
- What, if any, SDN is in use

Disk settings
- How big/fast are the disks used to host nodes?
- What are the log rates of the kubernetes components?

**Comment by thockin** [comment]
On Mon, Oct 3, 2016 at 7:12 AM, Matthew Mark Miller
notifications@github.com wrote:

> I'm very excited to see this project. I've been mentioning around the office for weeks that the community needs a better idea of how K8s is actually being used.
> 
> I'd like to help expand the project to collect more useful information about installations. Here's a dump of the things I've been wondering about that we could collect. I'd be willing to add any of these or help in the collection & anonymization of other datapoints.
> 
> Context (these would likely need to be provided in plain text at launch time, so wouldn't want to ask a lot)
> 
> Phase of cluster (e.g. prototype, development, staging, production)
> Installed in private datacenter or (specific) public cloud?

Careful on this last one.  It's _probably_ OK to send which
--cloud-provider, but that flag will eventually EOL and I'd rather not
lose useful info.

> Cluster setup
> 
> Master node count

Should show in in th einfo we have today, though we don't flag nodes
as masters, so ..

> Etcd node count
> Service node count
> Node volatility, how quickly are nodes added or removed from the cluster?
> Node consistency [specifically I wonder if master/etcd nodes are sized the same as other nodes]
> Are Etcd nodes also worker nodes (cf self hosting)
> 
> Networking
> -- Block size of Pod & Service networks
> -- Is an overlay network being used
> -- Is policy enabled
> -- Is CNI being used
> -- What, if any, SDN is in use

Careful not to collect anything potentially identifying.

> Disk settings
> 
> How big/fast are the disks used to host nodes?
> What are the log rates of the kubernetes components?

Currently we _only_ collect info that is available through the APi, so
you would have to extend API to collect these or else start collecting
from some metrics.
